apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: resume-builder
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: resume_db
  APP_THEMES_PATH: classpath:themes/
  EXPORT_CHROME_PATH: /usr/bin/chromium
