apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: resume-builder
type: Opaque
stringData:
  DB_USER: resume
  DB_PASS: resume123
  JWT_SECRET: resume-builder-k8s-secret-change-in-prod
