apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resume-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/129duckflew/resume-builder.git
    targetRevision: main
    path: k8s/app/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: resume-builder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
