apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-frontend
  namespace: resume-builder
  labels:
    app: resume-frontend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: resume-frontend
  template:
    metadata:
      labels:
        app: resume-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: frontend
          image: ghcr.io/129duckflew/resume-builder/frontend:8e20ecedbb326b5bfb4507102b000f3ca1cd231f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            exec:
              command:
                - wget
                - -qO-
                - http://127.0.0.1:80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - wget
                - -qO-
                - http://127.0.0.1:80
            initialDelaySeconds: 5
            periodSeconds: 5
